services:  
  postgres:
    image: postgres:latest
    container_name: SagaContext.Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sagacontext
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: no
    
volumes:
  postgres_data: